// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3WaYdEY3yONJyhMJ0jFUuhwu2x22WgZQ',
    appId: '1:209348611333:web:ead6e02f17ca5d0bb7bb6c',
    messagingSenderId: '209348611333',
    projectId: 'rate-my-class-4a24c',
    authDomain: 'rate-my-class-4a24c.firebaseapp.com',
    storageBucket: 'rate-my-class-4a24c.appspot.com',
    measurementId: 'G-H0SN72HX30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8tk1GOAd-mn4uMjdI74DPxd9DtYN2p_Q',
    appId: '1:209348611333:android:2e9c93fe8d06a442b7bb6c',
    messagingSenderId: '209348611333',
    projectId: 'rate-my-class-4a24c',
    storageBucket: 'rate-my-class-4a24c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATN43Kfnu_Q4wsCCfL8eaznW8Xh3qF7ek',
    appId: '1:209348611333:ios:db32a44323bd618ab7bb6c',
    messagingSenderId: '209348611333',
    projectId: 'rate-my-class-4a24c',
    storageBucket: 'rate-my-class-4a24c.appspot.com',
    iosClientId: '209348611333-95c7315lnk174od3rtsajo95kbffjg6g.apps.googleusercontent.com',
    iosBundleId: 'com.example.rateMyClas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATN43Kfnu_Q4wsCCfL8eaznW8Xh3qF7ek',
    appId: '1:209348611333:ios:db32a44323bd618ab7bb6c',
    messagingSenderId: '209348611333',
    projectId: 'rate-my-class-4a24c',
    storageBucket: 'rate-my-class-4a24c.appspot.com',
    iosClientId: '209348611333-95c7315lnk174od3rtsajo95kbffjg6g.apps.googleusercontent.com',
    iosBundleId: 'com.example.rateMyClas',
  );
}
